name: Snapshot

on:
  push:
    tags:
      - 'snapshot/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Cache ARM tools
      uses: actions/cache@v2
      env:
        cache-name: cache-arm-tools
      with:
        path: downloads/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
        key: gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux

    - name: Install ARM tools
      run: make arm_sdk_install

    - name: Set build variables
      run: echo "release=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Build HEX files for unified targets
      run: make unified SUFFIX=-${{ env.release }}

    - name: Move HEX
      run: mv obj/*.hex .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: heliflight-snapshot-${{ env.release }}
        path: heliflight*.hex

